version: '3.1'
services:
  oabs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: ['0.0.0.0:3000:3000']
    env_file:
      - ./.env
    environment:
      - APP_PORT=3000
